Binding.implementation ts correction
inversify/InversifyJS pull request #1127
Opened 2019-08-22 16:29 UTC by tonyhallett

## Description

This is being picky but for correctness.  For the generic T to be correct the implementationType type has to change otherwise T will be incorrect for cache/onActivation when toConstructor has been used to set the Binding.

## Related Issue

## Motivation and Context

It corrects the typescript - e.g no need for the BindingToSyntax to cast to any when setting the implementationType in the toConstructor method.

## How Has This Been Tested?

npm run test on Windows machine

## Types of changes

- [ ] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ x ] Breaking change (fix or feature that would cause existing functionality to change)
Yes if using the Binding.implementationType.
## Checklist:

- [ x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
No new tests required
- [ x ] All new and existing tests passed.
- [ ] I have updated the changelog.

2021-04-17 09:38 UTC, notaphplover approved these changes

2021-04-17 09:53 UTC, notaphplover requested changes
We are trying to avoid the use of any. As pointed previously, we shouldn't use the generic T in the implementationType property, but I think `unknown` is more appropiate even if additional casts may be added

2021-04-17 09:53 UTC, notaphplover commented on src/bindings/binding.ts
> +    public implementationType: interfaces.Newable<any> | null;
I would use `unknown` instead

2021-04-17 09:53 UTC, notaphplover commented on src/interfaces/interfaces.ts
> +        implementationType: Newable<any> | null;
I would use `unknown` instead

2021-04-29 21:03 UTC, tonyhallett commented
It is not just the implementationType that is incorrect.  Closing as this needs more consideration.

2021-04-29 21:03 UTC, closed without merging