docs: add zh-CN translations
inversify/InversifyJS pull request #1278
Opened 2020-12-31 10:43 UTC by Jeff-Tian

## Description

Hello, there! I love this great library and add zh-CN translations for it. Is it possible to get it merged? The deployed preview can be found here: https://inversifyjs.netlify.app/zh_cn/

## Related Issue

## Motivation and Context

Add zh-CN translations to motivate more Chinese developers to use InversifyJS.

## How Has This Been Tested?

Only documentation changes, deployed preview here: https://inversifyjs.netlify.app/zh_cn/

## Types of changes

- [x] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated the changelog.

2021-02-26 17:04 UTC, dcavanagh requested changes
Thank you for this. It looks like it was a lot of work. I made a few comments. I cannot review the CN language portions. We should have someone review them to back you up.

2021-02-26 17:04 UTC, dcavanagh commented on .vscode/settings.json
> -}
revert this please

2021-02-26 17:04 UTC, dcavanagh commented on wiki/en/README.md
> -Welcome to the InversifyJS wiki!
Revert this white space change please

2021-02-26 17:04 UTC, dcavanagh commented on netlify.toml
> +# example netlify.toml
What does netify do? Does this file need to be committed?

2021-02-26 17:04 UTC, dcavanagh commented on wiki/en/SUMMARY.md
> +# Wiki
Should this file be named README.md? It duplicates README.md and adds the translation

2021-02-26 17:04 UTC, dcavanagh commented on wiki/en/glossary.md
> +
Remove white space changes

2021-03-02 09:57 UTC, Jeff-Tian commented on netlify.toml
> +# example netlify.toml
Netlify is a static site host with CDN enabled. Highly recommend using it as github wiki is slow and can be error when accessing from China.

2021-03-02 09:58 UTC, Jeff-Tian commented on netlify.toml
> +# example netlify.toml
I've tested the deploying to netlify works: https://doc.inversify.cloud/zh_cn/

2021-03-02 09:59 UTC, Jeff-Tian commented on wiki/en/SUMMARY.md
> +# Wiki
Renaming it to SUMMARY.md to match the gitbook style. The gitbook is static site generator.

2021-03-02 14:15 UTC, dcavanagh commented
@Jeff-Tian  @NeoYo Are you able to have someone review the translation to back you up?

2021-03-03 01:47 UTC, Jeff-Tian commented
@dcavanagh thanks for your comments!



> @Jeff-Tian @NeoYo Are you able to have someone review the translation to back you up?

Not yet, but it's not urgent. Maybe just wait and let's see who can help in the future.

2022-03-15 14:36 UTC, jkhmtx commented
@Jeff-Tian @dcavanagh for a lack of another Chinese speaker to review this, I suggest that we give the benefit of the doubt and allow this to be merged after updating. What do you think?

2022-03-17 03:42 UTC, Jeff-Tian commented
Sure. Closing for now.

2022-03-17 03:42 UTC, closed without merging