Deactivation only for singleton
inversify/InversifyJS pull request #1335
Opened 2021-05-03 12:19 UTC by tonyhallett

fix #1334 

I did not suffix the error with 'Deactivation is for singletons.'  Add the suffix ?

2021-05-06 20:03 UTC, notaphplover requested changes
Just a minor change is requested

2021-05-06 20:03 UTC, notaphplover commented on src/resolution/instantiation.ts
>      }
We should use `BindingTypeEnum` instead

2021-05-07 11:56 UTC, tonyhallett commented on src/resolution/instantiation.ts
>      }
Ok

2021-05-07 21:43 UTC, notaphplover approved these changes
LGTM!

2021-05-07 21:43 UTC, notaphplover commented on test/resolution/resolver.test.ts
> +              //
if you want to remove the empty body warning, you can return `undefined` instead

2021-05-14 10:44 UTC, merged