feat(current-bound): add isCurrentBound for check dependency only in …
inversify/InversifyJS pull request #1354
Opened 2021-06-15 08:58 UTC by dmitry-nizovsky

add isCurrentBound for check dependency only in current container

## Description

add api method for user can check already registered dependency in container without bubbling checking to parent

## Related Issue

## Motivation and Context

Then I did integration InversifyJS with ReactJs I found one issue.
I cannot check bound dependency only current container.

## How Has This Been Tested?

## Types of changes

- [ ] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] I have updated the changelog.

2021-06-20 12:45 UTC, notaphplover requested changes
Looks good, I just suggested some minor changes

2021-06-20 12:45 UTC, notaphplover commented on package-lock.json
> +  "version": "5.1.1",
Version should not be updated

2021-06-20 12:45 UTC, notaphplover commented on package.json
> +  "version": "5.1.2",
Same

2021-06-20 12:45 UTC, notaphplover commented on CHANGELOG.md
> +## [5.1.2] - 2021-06-15
```suggestion
## [Unreleased]
```

2021-06-20 12:45 UTC, notaphplover commented on src/container/container.ts
> +    public isCurrentBound(serviceIdentifier: interfaces.ServiceIdentifier<any>): boolean {
```suggestion
    public isCurrentBound<T>(serviceIdentifier: interfaces.ServiceIdentifier<T>): boolean {
```

What about this? We try not to use any these days

2021-06-22 11:37 UTC, dmitry-nizovsky commented
Hello @notaphplover,
I did fix, Could you check again please?

2021-06-27 16:45 UTC, notaphplover approved these changes
LGTM!

2021-07-09 08:15 UTC, dmitry-nizovsky commented
Hello @notaphplover,
What should I do to merge this PR?

2021-07-28 04:17 UTC, dmitry-nizovsky commented
Hi @notaphplover,
Could you help me with merge PR please?

2021-08-22 17:59 UTC, merged