Improve "toFactory" type safety
inversify/InversifyJS pull request #1370
Opened 2021-08-23 12:11 UTC by LeonardSSH

Improvements by @GreenDou in https://github.com/inversify/InversifyJS/issues/569#issuecomment-755968007

Closes https://github.com/inversify/InversifyJS/issues/569

## Description

Improve "toFactory" type safety

## Related Issue

https://github.com/inversify/InversifyJS/issues/569

## Motivation and Context

https://github.com/inversify/InversifyJS/issues/569

## How Has This Been Tested?

## Types of changes

- [ ] Updated docs / Refactor code / Added a tests case (non-breaking change)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated the changelog.

2021-08-23 20:04 UTC, notaphplover requested changes
unknown should be better than any imo

2021-08-23 20:04 UTC, notaphplover commented on src/interfaces/interfaces.ts
> +    export type Factory<T, U extends any[] = any[]> = (...args: U) => (((...args: U) => T) | T);
```suggestion
    export type Factory<T, U extends unknown[] = unknown[]> = (...args: U) => (((...args: U) => T) | T);
```

2021-08-23 20:04 UTC, notaphplover commented on src/interfaces/interfaces.ts
> +        toFactory<T2, T3 extends any[] = any[]>(factory: FactoryCreator<T2, T3>): BindingWhenOnSyntax<T>;
```suggestion
        toFactory<T2, T3 extends unknown[] = unknown[]>(factory: FactoryCreator<T2, T3>): BindingWhenOnSyntax<T>;
```

2021-08-23 20:31 UTC, PodaruDragos approved these changes

2021-08-23 20:45 UTC, notaphplover approved these changes

2021-08-24 23:01 UTC, merged

2021-09-03 12:48 UTC, tonyhallett commented
This pull request has an introduced an error. https://github.com/inversify/InversifyJS/pull/1311#issuecomment-905480952

It has been corrected in https://github.com/inversify/InversifyJS/pull/1311
https://github.com/inversify/InversifyJS/blob/ee0a249c9c33e0dfb050aab41ded25c7473baa84/src/interfaces/interfaces.ts#L78

Also, please check wiki files when changing types.

Note that the correcting pull has not been merged yet.